### ISSUE TITLE
Why Estimate status doesn't match after adding a latent variable

### ISSUE THREAD

**Issue by Yuxi913** [FloSchuberth/cSEM#509] opened 2023-09-17 14:27 UTC
I firstly run a model below with three constructed latent variables, the summary suggested that estimation status is not ok. However, when I run a model later with the fourth latent variable that is constructed with these three latent variables, the summary suggested that estimation status is ok. I attached my models and their corresponding summaries below. Why the estimation status would change? What is the criteria of the estimation status? Thank you!

BD_all <- "
  PlantDiv =~ Plant_1 + Plant_2
  InvertDiv =~ Invert_1 + Invert_2
  FunDiv =~ Fun_1 + Fun_2
  
  Pasture_type <~ Pasturetype
  Grazing_T <~ GrazingT
  Burning_T <~ BurningT
  
  PlantDiv + InvertDiv + FunDiv ~ Pasture_type + Grazing_T + Burning_T"

> BD_all_res <- csem(.model = BD_all, .data = BiodivAll)
> (summary_BD_all_res <- summarize(BD_all_res))
________________________________________________________________________________
----------------------------------- Overview -----------------------------------

	General information:
	------------------------
	Estimation status                  = Not ok!
	Number of observations             = 78
	Weight estimator                   = PLS-PM
	Inner weighting scheme             = "path"
	Type of indicator correlation      = Pearson
	Path model estimator               = OLS
	Second-order approach              = NA
	Type of path model                 = Linear
	Disattenuated                      = Yes (PLSc)

	Construct details:
	------------------
	Name          Modeled as     Order         Mode      

	Pasture_type  Composite      First order   "modeB"   
	Grazing_T     Composite      First order   "modeB"   
	Burning_T     Composite      First order   "modeB"   
	PlantDiv      Common factor  First order   "modeA"   
	InvertDiv     Common factor  First order   "modeA"   
	FunDiv        Common factor  First order   "modeA"   

----------------------------------- Estimates ----------------------------------

Estimated path coefficients:
============================
  Path                        Estimate  Std. error   t-stat.   p-value
  PlantDiv ~ Pasture_type      -0.4481          NA        NA        NA
  PlantDiv ~ Grazing_T          0.2094          NA        NA        NA
  PlantDiv ~ Burning_T          0.1172          NA        NA        NA
  InvertDiv ~ Pasture_type      0.0199          NA        NA        NA
  InvertDiv ~ Grazing_T        -0.0598          NA        NA        NA
  InvertDiv ~ Burning_T        -0.1206          NA        NA        NA
  FunDiv ~ Pasture_type         0.1747          NA        NA        NA
  FunDiv ~ Grazing_T           -0.1478          NA        NA        NA
  FunDiv ~ Burning_T           -0.0934          NA        NA        NA

Estimated loadings:
===================
  Loading                        Estimate  Std. error   t-stat.   p-value
  Pasture_type =~ Pasturetype      1.0000          NA        NA        NA
  Grazing_T =~ GrazingT            1.0000          NA        NA        NA
  Burning_T =~ BurningT            1.0000          NA        NA        NA
  PlantDiv =~ Plant_1              0.9300          NA        NA        NA
  PlantDiv =~ Plant_2              1.0310          NA        NA        NA
  InvertDiv =~ Invert_1            0.9281          NA        NA        NA
  InvertDiv =~ Invert_2            0.6397          NA        NA        NA
  FunDiv =~ Fun_1                  0.9405          NA        NA        NA
  FunDiv =~ Fun_2                  0.5979          NA        NA        NA

Estimated weights:
==================
  Weight                         Estimate  Std. error   t-stat.   p-value
  Pasture_type <~ Pasturetype      1.0000          NA        NA        NA
  Grazing_T <~ GrazingT            1.0000          NA        NA        NA
  Burning_T <~ BurningT            1.0000          NA        NA        NA
  PlantDiv <~ Plant_1              0.4792          NA        NA        NA
  PlantDiv <~ Plant_2              0.5312          NA        NA        NA
  InvertDiv <~ Invert_1            0.6603          NA        NA        NA
  InvertDiv <~ Invert_2            0.4551          NA        NA        NA
  FunDiv <~ Fun_1                  0.6870          NA        NA        NA
  FunDiv <~ Fun_2                  0.4367          NA        NA        NA

Estimated construct correlations:
=================================
  Correlation                  Estimate  Std. error   t-stat.   p-value
  Pasture_type ~~ Grazing_T      0.0263          NA        NA        NA
  Pasture_type ~~ Burning_T      0.0263          NA        NA        NA
  Grazing_T ~~ Burning_T        -0.0263          NA        NA        NA

------------------------------------ Effects -----------------------------------

Estimated total effects:
========================
  Total effect                Estimate  Std. error   t-stat.   p-value
  PlantDiv ~ Pasture_type      -0.4481          NA        NA        NA
  PlantDiv ~ Grazing_T          0.2094          NA        NA        NA
  PlantDiv ~ Burning_T          0.1172          NA        NA        NA
  InvertDiv ~ Pasture_type      0.0199          NA        NA        NA
  InvertDiv ~ Grazing_T        -0.0598          NA        NA        NA
  InvertDiv ~ Burning_T        -0.1206          NA        NA        NA
  FunDiv ~ Pasture_type         0.1747          NA        NA        NA
  FunDiv ~ Grazing_T           -0.1478          NA        NA        NA
  FunDiv ~ Burning_T           -0.0934          NA        NA        NA
________________________________________________________________________________

BD_all <- "
  PlantDiv =~ Plant_1 + Plant_2
  InvertDiv =~ Invert_1 + Invert_2
  FunDiv =~ Fun_1 + Fun_2
  Biodiversity =~ PlantDiv + InvertDiv + FunDiv
  
  Pasture_type <~ Pasturetype
  Grazing_T <~ GrazingT
  Burning_T <~ BurningT
  
  Biodiversity ~ Pasture_type + Grazing_T + Burning_T"

> BD_all_res <- csem(.model = BD_all, .data = BiodivAll)
> (summary_BD_all_res <- summarize(BD_all_res))
________________________________________________________________________________
----------------------------------- Overview -----------------------------------

	General information:
	------------------------
	Estimation status                  = Ok
	Number of observations             = 78
	Weight estimator                   = PLS-PM
	Inner weighting scheme             = "path"
	Type of indicator correlation      = Pearson
	Path model estimator               = OLS
	Second-order approach              = 2stage
	Type of path model                 = Linear
	Disattenuated                      = First stage: Yes 
                                         = Second stage: Yes

	Construct details:
	------------------
	Name          Modeled as     Order         Mode      

	Pasture_type  Composite      First order   "modeB"   
	Grazing_T     Composite      First order   "modeB"   
	Burning_T     Composite      First order   "modeB"   
	PlantDiv      Common factor  First order   "modeA"   
	InvertDiv     Common factor  First order   "modeA"   
	FunDiv        Common factor  First order   "modeA"   
	Biodiversity  Common factor  Second order  "modeA"   

----------------------------------- Estimates ----------------------------------

Estimated path coefficients:
============================
  Path                           Estimate  Std. error   t-stat.   p-value
  Biodiversity ~ Pasture_type     -0.7293          NA        NA        NA
  Biodiversity ~ Grazing_T         0.3921          NA        NA        NA
  Biodiversity ~ Burning_T         0.2413          NA        NA        NA

Estimated loadings:
===================
  Loading                        Estimate  Std. error   t-stat.   p-value
  Pasture_type =~ Pasturetype      1.0000          NA        NA        NA
  Grazing_T =~ GrazingT            1.0000          NA        NA        NA
  Burning_T =~ BurningT            1.0000          NA        NA        NA
  PlantDiv =~ Plant_1              0.9390          NA        NA        NA
  PlantDiv =~ Plant_2              1.0211          NA        NA        NA
  InvertDiv =~ Invert_1            0.7219          NA        NA        NA
  InvertDiv =~ Invert_2            0.8224          NA        NA        NA
  FunDiv =~ Fun_1                  1.2236          NA        NA        NA
  FunDiv =~ Fun_2                  0.4595          NA        NA        NA
  Biodiversity =~ PlantDiv         0.5896          NA        NA        NA
  Biodiversity =~ InvertDiv       -0.0881          NA        NA        NA
  Biodiversity =~ FunDiv          -0.2279          NA        NA        NA

Estimated weights:
==================
  Weight                         Estimate  Std. error   t-stat.   p-value
  Pasture_type <~ Pasturetype      1.0000          NA        NA        NA
  Grazing_T <~ GrazingT            1.0000          NA        NA        NA
  Burning_T <~ BurningT            1.0000          NA        NA        NA
  PlantDiv <~ Plant_1              0.4840          NA        NA        NA
  PlantDiv <~ Plant_2              0.5264          NA        NA        NA
  InvertDiv <~ Invert_1            0.5234          NA        NA        NA
  InvertDiv <~ Invert_2            0.5962          NA        NA        NA
  FunDiv <~ Fun_1                  0.7998          NA        NA        NA
  FunDiv <~ Fun_2                  0.3004          NA        NA        NA
  Biodiversity <~ PlantDiv         0.8607          NA        NA        NA
  Biodiversity <~ InvertDiv       -0.1125          NA        NA        NA
  Biodiversity <~ FunDiv          -0.3746          NA        NA        NA

Estimated construct correlations:
=================================
  Correlation                  Estimate  Std. error   t-stat.   p-value
  Pasture_type ~~ Grazing_T      0.0263          NA        NA        NA
  Pasture_type ~~ Burning_T      0.0263          NA        NA        NA
  Grazing_T ~~ Burning_T        -0.0263          NA        NA        NA

------------------------------------ Effects -----------------------------------

Estimated total effects:
========================
  Total effect                   Estimate  Std. error   t-stat.   p-value
  Biodiversity ~ Pasture_type     -0.7293          NA        NA        NA
  Biodiversity ~ Grazing_T         0.3921          NA        NA        NA
  Biodiversity ~ Burning_T         0.2413          NA        NA        NA
________________________________________________________________________________

**Comment by FloSchuberth** [comment] 2023-09-17 15:10
Dear Yuxi,

You can get more details about the estimation status by using the verify() function on your cSEM results object, e.g., verify(BD_all_res).

Usually, at least one of the absolute standardized factor loadings is larger than 1 or at least one reliability estimate is larger than 1.

Best regards,
Florian

From: Yuxi Guo ***@***.***>
Sent: zondag 17 september 2023 16:28
To: FloSchuberth/cSEM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FloSchuberth/cSEM] Why Estimate status doesn't match after adding a latent variable (Issue #509)


I firstly run a model below with three constructed latent variables, the summary suggested that estimation status is not ok. However, when I run a model later with the fourth latent variable that is constructed with these three latent variables, the summary suggested that estimation status is ok. I attached my models and their corresponding summaries below. Why the estimation status would change? What is the criteria of the estimation status? Thank you!

BD_all <- "
PlantDiv =~ Plant_1 + Plant_2
InvertDiv =~ Invert_1 + Invert_2
FunDiv =~ Fun_1 + Fun_2

Pasture_type <~ Pasturetype
Grazing_T <~ GrazingT
Burning_T <~ BurningT

PlantDiv + InvertDiv + FunDiv ~ Pasture_type + Grazing_T + Burning_T"

BD_all_res <- csem(.model = BD_all, .data = BiodivAll)
(summary_BD_all_res <- summarize(BD_all_res))

________________________________

----------------------------------- Overview -----------------------------------

General information:

------------------------

Estimation status                  = Not ok!

Number of observations             = 78

Weight estimator                   = PLS-PM

Inner weighting scheme             = "path"

Type of indicator correlation      = Pearson

Path model estimator               = OLS

Second-order approach              = NA

Type of path model                 = Linear

Disattenuated                      = Yes (PLSc)



Construct details:

------------------

Name          Modeled as     Order         Mode



Pasture_type  Composite      First order   "modeB"

Grazing_T     Composite      First order   "modeB"

Burning_T     Composite      First order   "modeB"

PlantDiv      Common factor  First order   "modeA"

InvertDiv     Common factor  First order   "modeA"

FunDiv        Common factor  First order   "modeA"

----------------------------------- Estimates ----------------------------------

Estimated path coefficients:

Path Estimate Std. error t-stat. p-value
PlantDiv ~ Pasture_type -0.4481 NA NA NA
PlantDiv ~ Grazing_T 0.2094 NA NA NA
PlantDiv ~ Burning_T 0.1172 NA NA NA
InvertDiv ~ Pasture_type 0.0199 NA NA NA
InvertDiv ~ Grazing_T -0.0598 NA NA NA
InvertDiv ~ Burning_T -0.1206 NA NA NA
FunDiv ~ Pasture_type 0.1747 NA NA NA
FunDiv ~ Grazing_T -0.1478 NA NA NA
FunDiv ~ Burning_T -0.0934 NA NA NA

Estimated loadings:

Loading Estimate Std. error t-stat. p-value
Pasture_type =~ Pasturetype 1.0000 NA NA NA
Grazing_T =~ GrazingT 1.0000 NA NA NA
Burning_T =~ BurningT 1.0000 NA NA NA
PlantDiv =~ Plant_1 0.9300 NA NA NA
PlantDiv =~ Plant_2 1.0310 NA NA NA
InvertDiv =~ Invert_1 0.9281 NA NA NA
InvertDiv =~ Invert_2 0.6397 NA NA NA
FunDiv =~ Fun_1 0.9405 NA NA NA
FunDiv =~ Fun_2 0.5979 NA NA NA

Estimated weights:

Weight Estimate Std. error t-stat. p-value
Pasture_type <~ Pasturetype 1.0000 NA NA NA
Grazing_T <~ GrazingT 1.0000 NA NA NA
Burning_T <~ BurningT 1.0000 NA NA NA
PlantDiv <~ Plant_1 0.4792 NA NA NA
PlantDiv <~ Plant_2 0.5312 NA NA NA
InvertDiv <~ Invert_1 0.6603 NA NA NA
InvertDiv <~ Invert_2 0.4551 NA NA NA
FunDiv <~ Fun_1 0.6870 NA NA NA
FunDiv <~ Fun_2 0.4367 NA NA NA

Estimated construct correlations:

Correlation Estimate Std. error t-stat. p-value
Pasture_type ~~ Grazing_T 0.0263 NA NA NA
Pasture_type ~~ Burning_T 0.0263 NA NA NA
Grazing_T ~~ Burning_T -0.0263 NA NA NA

------------------------------------ Effects -----------------------------------

Estimated total effects:

Total effect Estimate Std. error t-stat. p-value
PlantDiv ~ Pasture_type -0.4481 NA NA NA
PlantDiv ~ Grazing_T 0.2094 NA NA NA
PlantDiv ~ Burning_T 0.1172 NA NA NA
InvertDiv ~ Pasture_type 0.0199 NA NA NA
InvertDiv ~ Grazing_T -0.0598 NA NA NA
InvertDiv ~ Burning_T -0.1206 NA NA NA
FunDiv ~ Pasture_type 0.1747 NA NA NA
FunDiv ~ Grazing_T -0.1478 NA NA NA
FunDiv ~ Burning_T -0.0934 NA NA NA

________________________________

BD_all <- "
PlantDiv =~ Plant_1 + Plant_2
InvertDiv =~ Invert_1 + Invert_2
FunDiv =~ Fun_1 + Fun_2
Biodiversity =~ PlantDiv + InvertDiv + FunDiv

Pasture_type <~ Pasturetype
Grazing_T <~ GrazingT
Burning_T <~ BurningT

Biodiversity ~ Pasture_type + Grazing_T + Burning_T"

BD_all_res <- csem(.model = BD_all, .data = BiodivAll)
(summary_BD_all_res <- summarize(BD_all_res))

________________________________

----------------------------------- Overview -----------------------------------

General information:

------------------------

Estimation status                  = Ok

Number of observations             = 78

Weight estimator                   = PLS-PM

Inner weighting scheme             = "path"

Type of indicator correlation      = Pearson

Path model estimator               = OLS

Second-order approach              = 2stage

Type of path model                 = Linear

Disattenuated                      = First stage: Yes

                                     = Second stage: Yes



Construct details:

------------------

Name          Modeled as     Order         Mode



Pasture_type  Composite      First order   "modeB"

Grazing_T     Composite      First order   "modeB"

Burning_T     Composite      First order   "modeB"

PlantDiv      Common factor  First order   "modeA"

InvertDiv     Common factor  First order   "modeA"

FunDiv        Common factor  First order   "modeA"

Biodiversity  Common factor  Second order  "modeA"

----------------------------------- Estimates ----------------------------------

Estimated path coefficients:

Path Estimate Std. error t-stat. p-value
Biodiversity ~ Pasture_type -0.7293 NA NA NA
Biodiversity ~ Grazing_T 0.3921 NA NA NA
Biodiversity ~ Burning_T 0.2413 NA NA NA

Estimated loadings:

Loading Estimate Std. error t-stat. p-value
Pasture_type =~ Pasturetype 1.0000 NA NA NA
Grazing_T =~ GrazingT 1.0000 NA NA NA
Burning_T =~ BurningT 1.0000 NA NA NA
PlantDiv =~ Plant_1 0.9390 NA NA NA
PlantDiv =~ Plant_2 1.0211 NA NA NA
InvertDiv =~ Invert_1 0.7219 NA NA NA
InvertDiv =~ Invert_2 0.8224 NA NA NA
FunDiv =~ Fun_1 1.2236 NA NA NA
FunDiv =~ Fun_2 0.4595 NA NA NA
Biodiversity =~ PlantDiv 0.5896 NA NA NA
Biodiversity =~ InvertDiv -0.0881 NA NA NA
Biodiversity =~ FunDiv -0.2279 NA NA NA

Estimated weights:

Weight Estimate Std. error t-stat. p-value
Pasture_type <~ Pasturetype 1.0000 NA NA NA
Grazing_T <~ GrazingT 1.0000 NA NA NA
Burning_T <~ BurningT 1.0000 NA NA NA
PlantDiv <~ Plant_1 0.4840 NA NA NA
PlantDiv <~ Plant_2 0.5264 NA NA NA
InvertDiv <~ Invert_1 0.5234 NA NA NA
InvertDiv <~ Invert_2 0.5962 NA NA NA
FunDiv <~ Fun_1 0.7998 NA NA NA
FunDiv <~ Fun_2 0.3004 NA NA NA
Biodiversity <~ PlantDiv 0.8607 NA NA NA
Biodiversity <~ InvertDiv -0.1125 NA NA NA
Biodiversity <~ FunDiv -0.3746 NA NA NA

Estimated construct correlations:

Correlation Estimate Std. error t-stat. p-value
Pasture_type ~~ Grazing_T 0.0263 NA NA NA
Pasture_type ~~ Burning_T 0.0263 NA NA NA
Grazing_T ~~ Burning_T -0.0263 NA NA NA

------------------------------------ Effects -----------------------------------

Estimated total effects:

Total effect Estimate Std. error t-stat. p-value
Biodiversity ~ Pasture_type -0.7293 NA NA NA
Biodiversity ~ Grazing_T 0.3921 NA NA NA
Biodiversity ~ Burning_T 0.2413 NA NA NA

________________________________

-

**Comment by Yuxi913** [comment] 2023-09-18 01:10
Hi Florian,

Thank you so much for the quick response, which perfectly answered my question.

Best regards,
Yuxi

From: FloSchuberth ***@***.***>
Date: Sunday, September 17, 2023 at 11:10 AM
To: FloSchuberth/cSEM ***@***.***>
Cc: Guo,Yuxi ***@***.***>, Author ***@***.***>
Subject: Re: [FloSchuberth/cSEM] Why Estimate status doesn't match after adding a latent variable (Issue #509)
[External Email]
Dear Yuxi,

You can get more details about the estimation status by using the verify() function on your cSEM results object, e.g., verify(BD_all_res).

Usually, at least one of the absolute standardized factor loadings is larger than 1 or at least one reliability estimate is larger than 1.

Best regards,
Florian

From: Yuxi Guo ***@***.***>
Sent: zondag 17 september 2023 16:28
To: FloSchuberth/cSEM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FloSchuberth/cSEM] Why Estimate status doesn't match after adding a latent variable (Issue #509)


I firstly run a model below with three constructed latent variables, the summary suggested that estimation status is not ok. However, when I run a model later with the fourth latent variable that is constructed with these three latent variables, the summary suggested that estimation status is ok. I attached my models and their corresponding summaries below. Why the estimation status would change? What is the criteria of the estimation status? Thank you!

BD_all <- "
PlantDiv =~ Plant_1 + Plant_2
InvertDiv =~ Invert_1 + Invert_2
FunDiv =~ Fun_1 + Fun_2

Pasture_type <~ Pasturetype
Grazing_T <~ GrazingT
Burning_T <~ BurningT

PlantDiv + InvertDiv + FunDiv ~ Pasture_type + Grazing_T + Burning_T"

BD_all_res <- csem(.model = BD_all, .data = BiodivAll)
(summary_BD_all_res <- summarize(BD_all_res))

________________________________

----------------------------------- Overview -----------------------------------

General information:

------------------------

Estimation status = Not ok!

Number of observations = 78

Weight estimator = PLS-PM

Inner weighting scheme = "path"

Type of indicator correlation = Pearson

Path model estimator = OLS

Second-order approach = NA

Type of path model = Linear

Disattenuated = Yes (PLSc)



Construct details:

------------------

Name Modeled as Order Mode



Pasture_type Composite First order "modeB"

Grazing_T Composite First order "modeB"

Burning_T Composite First order "modeB"

PlantDiv Common factor First order "modeA"

InvertDiv Common factor First order "modeA"

FunDiv Common factor First order "modeA"

----------------------------------- Estimates ----------------------------------

Estimated path coefficients:

Path Estimate Std. error t-stat. p-value
PlantDiv ~ Pasture_type -0.4481 NA NA NA
PlantDiv ~ Grazing_T 0.2094 NA NA NA
PlantDiv ~ Burning_T 0.1172 NA NA NA
InvertDiv ~ Pasture_type 0.0199 NA NA NA
InvertDiv ~ Grazing_T -0.0598 NA NA NA
InvertDiv ~ Burning_T -0.1206 NA NA NA
FunDiv ~ Pasture_type 0.1747 NA NA NA
FunDiv ~ Grazing_T -0.1478 NA NA NA
FunDiv ~ Burning_T -0.0934 NA NA NA

Estimated loadings:

Loading Estimate Std. error t-stat. p-value
Pasture_type =~ Pasturetype 1.0000 NA NA NA
Grazing_T =~ GrazingT 1.0000 NA NA NA
Burning_T =~ BurningT 1.0000 NA NA NA
PlantDiv =~ Plant_1 0.9300 NA NA NA
PlantDiv =~ Plant_2 1.0310 NA NA NA
InvertDiv =~ Invert_1 0.9281 NA NA NA
InvertDiv =~ Invert_2 0.6397 NA NA NA
FunDiv =~ Fun_1 0.9405 NA NA NA
FunDiv =~ Fun_2 0.5979 NA NA NA

Estimated weights:

Weight Estimate Std. error t-stat. p-value
Pasture_type <~ Pasturetype 1.0000 NA NA NA
Grazing_T <~ GrazingT 1.0000 NA NA NA
Burning_T <~ BurningT 1.0000 NA NA NA
PlantDiv <~ Plant_1 0.4792 NA NA NA
PlantDiv <~ Plant_2 0.5312 NA NA NA
InvertDiv <~ Invert_1 0.6603 NA NA NA
InvertDiv <~ Invert_2 0.4551 NA NA NA
FunDiv <~ Fun_1 0.6870 NA NA NA
FunDiv <~ Fun_2 0.4367 NA NA NA

Estimated construct correlations:

Correlation Estimate Std. error t-stat. p-value
Pasture_type ~~ Grazing_T 0.0263 NA NA NA
Pasture_type ~~ Burning_T 0.0263 NA NA NA
Grazing_T ~~ Burning_T -0.0263 NA NA NA

------------------------------------ Effects -----------------------------------

Estimated total effects:

Total effect Estimate Std. error t-stat. p-value
PlantDiv ~ Pasture_type -0.4481 NA NA NA
PlantDiv ~ Grazing_T 0.2094 NA NA NA
PlantDiv ~ Burning_T 0.1172 NA NA NA
InvertDiv ~ Pasture_type 0.0199 NA NA NA
InvertDiv ~ Grazing_T -0.0598 NA NA NA
InvertDiv ~ Burning_T -0.1206 NA NA NA
FunDiv ~ Pasture_type 0.1747 NA NA NA
FunDiv ~ Grazing_T -0.1478 NA NA NA
FunDiv ~ Burning_T -0.0934 NA NA NA

________________________________

BD_all <- "
PlantDiv =~ Plant_1 + Plant_2
InvertDiv =~ Invert_1 + Invert_2
FunDiv =~ Fun_1 + Fun_2
Biodiversity =~ PlantDiv + InvertDiv + FunDiv

Pasture_type <~ Pasturetype
Grazing_T <~ GrazingT
Burning_T <~ BurningT

Biodiversity ~ Pasture_type + Grazing_T + Burning_T"

BD_all_res <- csem(.model = BD_all, .data = BiodivAll)
(summary_BD_all_res <- summarize(BD_all_res))

________________________________

----------------------------------- Overview -----------------------------------

General information:

------------------------

Estimation status = Ok

Number of observations = 78

Weight estimator = PLS-PM

Inner weighting scheme = "path"

Type of indicator correlation = Pearson

Path model estimator = OLS

Second-order approach = 2stage

Type of path model = Linear

Disattenuated = First stage: Yes

= Second stage: Yes



Construct details:

------------------

Name Modeled as Order Mode



Pasture_type Composite First order "modeB"

Grazing_T Composite First order "modeB"

Burning_T Composite First order "modeB"

PlantDiv Common factor First order "modeA"

InvertDiv Common factor First order "modeA"

FunDiv Common factor First order "modeA"

Biodiversity Common factor Second order "modeA"

----------------------------------- Estimates ----------------------------------

Estimated path coefficients:

Path Estimate Std. error t-stat. p-value
Biodiversity ~ Pasture_type -0.7293 NA NA NA
Biodiversity ~ Grazing_T 0.3921 NA NA NA
Biodiversity ~ Burning_T 0.2413 NA NA NA

Estimated loadings:

Loading Estimate Std. error t-stat. p-value
Pasture_type =~ Pasturetype 1.0000 NA NA NA
Grazing_T =~ GrazingT 1.0000 NA NA NA
Burning_T =~ BurningT 1.0000 NA NA NA
PlantDiv =~ Plant_1 0.9390 NA NA NA
PlantDiv =~ Plant_2 1.0211 NA NA NA
InvertDiv =~ Invert_1 0.7219 NA NA NA
InvertDiv =~ Invert_2 0.8224 NA NA NA
FunDiv =~ Fun_1 1.2236 NA NA NA
FunDiv =~ Fun_2 0.4595 NA NA NA
Biodiversity =~ PlantDiv 0.5896 NA NA NA
Biodiversity =~ InvertDiv -0.0881 NA NA NA
Biodiversity =~ FunDiv -0.2279 NA NA NA

Estimated weights:

Weight Estimate Std. error t-stat. p-value
Pasture_type <~ Pasturetype 1.0000 NA NA NA
Grazing_T <~ GrazingT 1.0000 NA NA NA
Burning_T <~ BurningT 1.0000 NA NA NA
PlantDiv <~ Plant_1 0.4840 NA NA NA
PlantDiv <~ Plant_2 0.5264 NA NA NA
InvertDiv <~ Invert_1 0.5234 NA NA NA
InvertDiv <~ Invert_2 0.5962 NA NA NA
FunDiv <~ Fun_1 0.7998 NA NA NA
FunDiv <~ Fun_2 0.3004 NA NA NA
Biodiversity <~ PlantDiv 0.8607 NA NA NA
Biodiversity <~ InvertDiv -0.1125 NA NA NA
Biodiversity <~ FunDiv -0.3746 NA NA NA

Estimated construct correlations:

Correlation Estimate Std. error t-stat. p-value
Pasture_type ~~ Grazing_T 0.0263 NA NA NA
Pasture_type ~~ Burning_T 0.0263 NA NA NA
Grazing_T ~~ Burning_T -0.0263 NA NA NA

------------------------------------ Effects -----------------------------------

Estimated total effects:

Total effect Estimate Std. error t-stat. p-value
Biodiversity ~ Pasture_type -0.7293 NA NA NA
Biodiversity ~ Grazing_T 0.3921 NA NA NA
Biodiversity ~ Burning_T 0.2413 NA NA NA

________________________________

-

**Comment by FloSchuberth** [comment] 2023-09-18 06:56
Dear Yuxi,

You are welcome. Since the issue is solved, I closed it.

Best regards,
Florian

**Closed** 2023-09-18 06:56 UTC
